# -*- coding: utf-8 -*-
"""Asl_model_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuKywtKYRaxY4EAXVH_T0FitTKoYroGs
"""

# =============================================
# 📦 SETUP
# =============================================
!pip install -q gradio torch torchvision

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import gradio as gr

# =============================================
# ⚙️ LOAD YOUR TRAINED MODEL (PyTorch ≥2.6 fix)
# =============================================
from torchvision.models import resnet
torch.serialization.add_safe_globals([resnet.ResNet])

MODEL_PATH = "/content/drive/MyDrive/resnet3_model_full.pth"

# Load the full model (since you saved torch.save(model))
model = torch.load(MODEL_PATH, map_location="cpu", weights_only=False)
model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# =============================================
# 🧠 DEFINE TRANSFORM (must match training)
# =============================================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# =============================================
# 🔤 DEFINE CLASS LABELS (Digits + A–Z + 3 extras)
# =============================================
digits = [str(i) for i in range(10)]              # 0–9
letters = [chr(i) for i in range(ord('A'), ord('Z')+1)]  # A–Z
extras = ["del", "space", "nothing"]              # customize if needed

classes = digits + letters + extras               # total 39 classes

# =============================================
# 🔍 PREDICTION FUNCTION
# =============================================
def predict(img):
    img = img.convert("RGB")
    input_tensor = transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.nn.functional.softmax(outputs, dim=1)
        conf, predicted = torch.max(probs, 1)

    label = classes[predicted.item()]
    confidence = float(conf.item()) * 100
    return f"{label} ({confidence:.2f}% confidence)"

# =============================================
# 🎥 GRADIO INTERFACE (works with Gradio 5+)
# =============================================
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil", label="Show your hand sign (webcam supported on mobile)"),
    outputs=gr.Textbox(label="Prediction"),
    live=True,
    title="ASL Sign Language Recognition",
    description="Open this link on your phone, allow camera, and show a hand sign!"
)

# =============================================
# 🚀 LAUNCH (get gradio.live link)
# =============================================
demo.launch(share=True)